<?php
/**
 * ROYAL JUBILANT — ADMIN RECOVERY SCRIPT (PHP version)
 *
 * Use this when `node` is not in PATH on Hostinger SSH.
 * PHP is always available on Hostinger.
 *
 * Run via SSH:
 *   cd domains/royaljubilant.com/public_html
 *   php scripts/recover-admin.php
 *
 * This script:
 * 1. Connects to MySQL with the correct password
 * 2. Checks if User table exists; if not, creates it (minimal schema)
 * 3. Inserts/updates admin user with admin123 password
 * 4. Reports success
 *
 * The bcrypt hash generated by PHP's password_hash() is fully compatible
 * with Node.js bcryptjs (both use $2b$ prefix format).
 */

// ═══════════════════════════════════════════════════════════
// CONFIG — hardcoded so it works regardless of .env
// ═══════════════════════════════════════════════════════════

$MYSQL_HOST = 'localhost';
$MYSQL_DB   = 'u432212399_rjcom';
$MYSQL_USER = 'u432212399_adminrjcom';
$MYSQL_PASS = 'Admin@2026@#';

$ADMIN_EMAIL    = 'admin@royaljubilant.ae';
$ADMIN_PASSWORD = 'admin123';
$ADMIN_NAME     = 'Royal Jubilant Admin';

echo "═══════════════════════════════════════════════════════\n";
echo "  ROYAL JUBILANT — ADMIN RECOVERY (PHP)\n";
echo "═══════════════════════════════════════════════════════\n\n";

// ═══════════════════════════════════════════════════════════
// STEP 1: Connect to MySQL
// ═══════════════════════════════════════════════════════════

echo "[1/5] Connecting to MySQL...\n";
echo "      Host: $MYSQL_HOST\n";
echo "      DB:   $MYSQL_DB\n";
echo "      User: $MYSQL_USER\n\n";

$conn = @new mysqli($MYSQL_HOST, $MYSQL_USER, $MYSQL_PASS, $MYSQL_DB);
if ($conn->connect_error) {
    echo "[FAIL] MySQL connection failed: " . $conn->connect_error . "\n\n";
    echo "Possible causes:\n";
    echo "  1. Database '$MYSQL_DB' does not exist (create it in hPanel → MySQL Databases)\n";
    echo "  2. User '$MYSQL_USER' does not have access to this database\n";
    echo "  3. Password is wrong (expected: Admin@2026@#)\n";
    exit(1);
}
echo "[OK] Connected to MySQL\n\n";

// ═══════════════════════════════════════════════════════════
// STEP 2: Check if User table exists
// ═══════════════════════════════════════════════════════════

echo "[2/5] Checking for User table...\n";

$tableFound = null;
$candidates = ['User', 'user', 'USER'];
foreach ($candidates as $t) {
    $r = $conn->query("SHOW TABLES LIKE '$t'");
    if ($r && $r->num_rows > 0) {
        $tableFound = $t;
        break;
    }
}

if ($tableFound) {
    echo "[OK] Found table: $tableFound\n\n";
} else {
    echo "[INFO] User table not found. Creating minimal schema...\n";
    
    // Create User table with Prisma-compatible schema
    $sql = "CREATE TABLE IF NOT EXISTS `User` (
        `id` VARCHAR(128) NOT NULL PRIMARY KEY,
        `email` VARCHAR(255) NOT NULL UNIQUE,
        `name` VARCHAR(255),
        `phone` VARCHAR(255),
        `role` VARCHAR(50) NOT NULL DEFAULT 'customer',
        `passwordHash` TEXT,
        `avatarUrl` TEXT,
        `preferredLang` VARCHAR(20),
        `googleId` VARCHAR(255),
        `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
        `updatedAt` DATETIME(3) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
    
    if (!$conn->query($sql)) {
        echo "[FAIL] Could not create User table: " . $conn->error . "\n";
        exit(1);
    }
    $tableFound = 'User';
    echo "[OK] Created User table\n\n";
}

// ═══════════════════════════════════════════════════════════
// STEP 3: Generate bcrypt password hash
// ═══════════════════════════════════════════════════════════

echo "[3/5] Generating bcrypt password hash...\n";
$hash = password_hash($ADMIN_PASSWORD, PASSWORD_BCRYPT);
if (!$hash) {
    echo "[FAIL] password_hash() failed\n";
    exit(1);
}
echo "[OK] Hash: " . substr($hash, 0, 30) . "...\n\n";

// ═══════════════════════════════════════════════════════════
// STEP 4: Insert or update admin user
// ═══════════════════════════════════════════════════════════

echo "[4/5] Creating/updating admin user...\n";
echo "      Email:    $ADMIN_EMAIL\n";
echo "      Password: $ADMIN_PASSWORD\n";
echo "      Role:     admin\n\n";

// Check if admin exists
$stmt = $conn->prepare("SELECT id FROM `$tableFound` WHERE email = ?");
$stmt->bind_param('s', $ADMIN_EMAIL);
$stmt->execute();
$result = $stmt->get_result();

if ($result && $result->num_rows > 0) {
    // Update existing
    $stmt->close();
    $stmt = $conn->prepare("UPDATE `$tableFound` SET passwordHash = ?, role = 'admin', name = ?, updatedAt = NOW() WHERE email = ?");
    $stmt->bind_param('sss', $hash, $ADMIN_NAME, $ADMIN_EMAIL);
    if ($stmt->execute()) {
        echo "[OK] Existing admin user updated.\n";
    } else {
        echo "[FAIL] Update failed: " . $stmt->error . "\n";
        exit(1);
    }
} else {
    // Insert new
    $stmt->close();
    $id = 'c' . bin2hex(random_bytes(12)); // cuid-like format
    $stmt = $conn->prepare("INSERT INTO `$tableFound` (id, email, name, role, passwordHash, createdAt, updatedAt) VALUES (?, ?, ?, 'admin', ?, NOW(), NOW())");
    $stmt->bind_param('ssss', $id, $ADMIN_EMAIL, $ADMIN_NAME, $hash);
    if ($stmt->execute()) {
        echo "[OK] New admin user created with ID: $id\n";
    } else {
        echo "[FAIL] Insert failed: " . $stmt->error . "\n";
        exit(1);
    }
}
$stmt->close();

// ═══════════════════════════════════════════════════════════
// STEP 5: Verify
// ═══════════════════════════════════════════════════════════

echo "\n[5/5] Verifying admin user...\n";
$stmt = $conn->prepare("SELECT id, email, name, role, LEFT(passwordHash, 20) as hash_prefix FROM `$tableFound` WHERE email = ?");
$stmt->bind_param('s', $ADMIN_EMAIL);
$stmt->execute();
$result = $stmt->get_result();
if ($result && $row = $result->fetch_assoc()) {
    echo "[OK] Admin user verified:\n";
    echo "      ID:    " . $row['id'] . "\n";
    echo "      Email: " . $row['email'] . "\n";
    echo "      Name:  " . $row['name'] . "\n";
    echo "      Role:  " . $row['role'] . "\n";
    echo "      Hash:  " . $row['hash_prefix'] . "...\n";
} else {
    echo "[FAIL] Could not verify admin user.\n";
    exit(1);
}
$stmt->close();
$conn->close();

// ═══════════════════════════════════════════════════════════
// DONE
// ═══════════════════════════════════════════════════════════

echo "\n═══════════════════════════════════════════════════════\n";
echo "  RECOVERY COMPLETE!\n";
echo "═══════════════════════════════════════════════════════\n\n";
echo "You can now log in at:\n";
echo "  https://www.royaljubilant.com/admin/login\n\n";
echo "Credentials:\n";
echo "  Email:    $ADMIN_EMAIL\n";
echo "  Password: $ADMIN_PASSWORD\n\n";
echo "If login still fails after this, the issue is likely:\n";
echo "  1. NextAuth not configured properly → check .env file\n";
echo "  2. App needs restart → hPanel → Advanced → Node.js → Restart\n";
echo "  3. Database connection in app uses wrong env → check app-hostinger.js\n";
